version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8888:80'
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    depends_on:
        - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=uea123
      - MYSQL_DATABASE=controle_financas
      - MYSQL_USER=chris
      - MYSQL_PASSWORD=uea123
